# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 693c8d6bbc1bf32e828a778716357b0e1ece62bdb310cf417fb6498b0e28742ab28d44b11858060d8995d7d6ab15d2f94e809dd1bcf2ad59b87143b35689826e

test:
  secret_key_base: c115b693fb24a7fd47af8f73748709807060e27cdd9c4eec652881a0f58d1be728ac291e7cd6b77f7d0c9a57c4e0232b5d4ebb8113d37c367e79bd55d017b0b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
